services:
  app:
    depends_on:
    - db
    image: antmbx/devops-for-programmers-project-74
    build:
        context: .
        dockerfile: Dockerfile.production
  


  caddy:
    depends_on:
    - app
    #image: hexletcomponents/devops-example-caddy
    image: caddy:2.8.4-alpine

  db:
    image: postgres
    restart: always
    #env_file: db.env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5