
services:
  app:
    hostname: app
    build:
        context: .
        dockerfile: ./Dockerfile
    command: make dev
    ports:
    - 8080:8080
    
    volumes:
    - ./app:/app

    environment:
    - NODE_ENV=development 

  caddy:
    ports:
    - 80:80
    - 443:443

    volumes:
    - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    - ./app:/app 
    

    
    