services:
  app:
    depends_on:
    - db
    image: antmbx/devops-for-programmers-project-74
    build:
        context: .
        dockerfile: Dockerfile.production
 

  db:
    image: postgres
    restart: always
    
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5