
services:
  app:
    hostname: app
    build:
        context: .
        dockerfile: ./Dockerfile
    command: make dev
    ports:
    - 8080:8080
    
    volumes:
    - ./app:/app

    environment:
    - NODE_ENV=development 
    
  
    


  caddy:
    depends_on:
      - app
    image: caddy:2.8.4-alpine
    #build:
        #context: .
        #dockerfile: ./Dockerfile
    #command: make dev
    ports:
    - 80:80
    - 443:443

    volumes:
    - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
        

    links:
      - app:app    
    

    
    