
services:
  app:
    
    build:
        context: .
        dockerfile: ./Dockerfile
    command: make dev
    ports:
    - 8080:8080
    
    volumes:
    - ./app:/app

  caddy:
    depends_on:
      - app
    image: caddy:2.8
    #build:
        #context: .
        #dockerfile: ./Dockerfile
    #command: make dev
    ports:
    - 80:80
    - 443:443

    volumes:
    - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile