name: push

on:
  push:
    branches:
      - main

env:
  CI: true
  APP_IMAGE_NAME: antmbx/devops-for-programmers-project-74   


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build App
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}
          cache-to: type=inline
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest
        
      - run: make compose-test